[project]
name = "dspy_pipeline"
dynamic = ["version"]
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "dspy>=3.0.4",
    "kagglehub>=0.3.13",
    "pandas>=2.2.0",
    "scikit-learn>=1.6.1",
]
